# Generated by Django 6.0.6 on 2026-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.CharField(max_length=4)),
                ('number_plate', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tyre_change', 'Tyre Change'), ('brake_service', 'Brake Service'), ('engine_repair', 'Engine Repair'), ('electrical', 'Electrical Repair'), ('body_work', 'Body Work'), ('full_service', 'Full Service'), ('diagnostics', 'Vehicle Diagnostics'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Any extra details about the problem')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mechanic_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['preferred_date', 'preferred_time'],
            },
        ),
    ]
